export const PROJECTS_DETAILS = [
  {
    id: 'maisons-du-monde',
    type: 'pro',
    title: 'Développeuse front-end Vue 3',
    company: 'Maisons du Monde',
    link: '/project/maisons-du-monde',
    dates: `2021 - aujourd'hui`,
    context: 'Refonte du site e-commerce Maisons du Monde',
    description: 'Refonte du site e-commerce Maisons du Monde',
    size: 'large',
    list: [
      `Refonte front-end et back-for-front en SSR avec Vue 3 composition API, TypeScript, Node, Koa, Tailwind, GraphQL`,
      `Maintenance évolutive : amélioration continue du site pour répondre aux enjeux commerciaux`,
      `Développement d’applications spécifiques pour les vendeurs, entrepôt et un back-office`,
      `Cadrage et développement du Design System : collaboration avec l’équipe UX/UI pour la conception des composants, visualisation via Histoire et Storybook`,
      `Mise en place de tests unitaires et end-to-end en TDD avec Vitest`,
      `Développement pour le headless CMS Prismic pour une gestion de contenu en autonomie par l’équipe marketing`,
      `Travail en méthodologie Agile Scrum avec des démo régulières aux clients internes`,
      `Release management : supervision des déploiements en production`,
      `Performances : suivi des Web Vitals et optimisation`,
      `Monitoring et analyse : suivi des performances et des erreurs en temps réel avec New Relic`,
      `SEO : optimisation SEO pour améliorer la visibilité du site`,
      `A/B tests avec Unleash et AB Tasty, suivi des performances avec Google Analytics et Tag Commander`,
    ],
    image: 'mdm-1.png',
    stack: [
      'Vue 3',
      'Node.js',
      'Tailwind CSS',
      'GraphQL',
      'Prismic CMS',
      'Vitest',
      'Vite',
      'New Relic',
    ],
  },
  {
    id: 'fiters',
    type: 'pro',
    title: 'Développeuse full-stack JS',
    company: 'Fiters',
    link: '/project/fiters',
    dates: `février 2021 - septembre 2021 (8 mois)`,
    context:
      'Fiters est une entreprise qui propose des solutions et programmes de coaching sportif en entreprise',
    description: `Refonte du site vitrine et développement sur les 3 webapps`,
    size: 'small',
    list: [
      `Refonte du site vitrine : utilisation de Vue 2 avec Quasar pour le front-end et Node.js et Firebase pour le développement back-end et la gestion de la base de données en temps réel`,
      `Développement de trois webapps dédiées : application destinée aux coachs sportifs, tableau de bord pour les entreprises clientes, et application destinée aux collaborateurs des entreprises`,
      `Mise en place du headless CMS Contentful permettant aux équipes marketing de mettre à jour le site en autonomie`,
      `Collaboration client et suivi : échanges avec les clients pour comprendre leurs besoins, fournir des mises à jour`,
    ],
    image: 'fiters-1.png',
    stack: ['Vue 2', 'Node.js', 'Firebase', 'Headless CMS Contentful '],
  },
  {
    id: 'bnp-paribas',
    type: 'pro',
    title: 'Product owner',
    company: 'BNP Paribas',
    link: '/project/bnp-paribas',
    dates: `octobre 2016 - mars 2020 (3 ans et demi)`,
    context:
      'Développement d’un intranet destiné à l’ensemble du Groupe BNP Paribas (280k collaborateurs)',
    description: `Refonte de l'intranet du Groupe`,
    size: 'small',
    list: [],
    image: 'bnpparibas-1.png',
    stack: [],
  },
  {
    id: 'bnp-paribas-webdesigner',
    type: 'pro',
    title: 'Webdesigner, alternance',
    company: 'BNP Paribas',
    link: '',
    dates: `Octobre 2014 à Septembre 2016 (2 ans)`,
    context: '',
    description: '',
    size: 'small',
    list: [],
    image: '',
    stack: [],
  },
  {
    id: 'pomodoro-timer',
    type: 'other',
    title: 'Pomodoro timer',
    link: '/project/pomodoro-timer',
    description: 'Un timer basé sur la méthode Pomodoro',
    image: 'pomodoro-1.png',
    size: 'large',
    stack: ['React', 'Typescript', 'Tailwind'],
  },
  {
    id: 'medium',
    type: 'other',
    title: 'Medium',
    link: '/project/medium',
    description: 'Copycat du site Medium',
    image: 'medium.png',
    size: 'small',
    stack: ['React', 'Typescript', 'Tailwind'],
  },
  {
    id: 'todo-app',
    type: 'other',
    title: 'Todo app',
    link: '/project/todo-app',
    description: 'Juste une autre todo app',
    image: 'todoapp.png',
    size: 'small',
    stack: ['React', 'Typescript', 'Tailwind'],
  },
]

export const EDUCATION = [
  {
    title: 'Software craftsmanship TDD',
    company: 'Human Coders',
    dates: '2024',
  },
  {
    title: 'Vue3 Composition API avancé',
    company: 'Human Coders',
    dates: '2023',
  },
  {
    title: `Concepteur développeur d'applications`,
    company: 'Afpa',
    dates: '2020 - 2021',
  },
  {
    title: 'Agile Scrum',
    company: 'Esic',
    dates: '2018',
  },
  {
    title: 'Master Cultures et Métiers du Web',
    company: 'Université Gustave Eiffel',
    dates: '2014 - 2016',
  },
  {
    title: 'Licence Infographie et Webdesign',
    company: 'Université Sorbonne Paris Nord',
    dates: '2011 - 2014',
  },
]

export const TOOLS = [
  {
    name: 'Vue 3 Composition API',
    type: 'Framework',
    icon: 'vuejs',
    category: 'framework',
  },
  {
    name: 'React',
    type: 'Framework',
    icon: 'react',
    category: 'framework',
  },
  {
    name: 'Typescript',
    type: 'Langage',
    icon: 'typescript',
    category: 'language',
  },
  {
    name: 'JavaScript',
    type: 'Langage',
    icon: 'javascript',
    category: 'language',
  },
  {
    name: 'NextJS',
    type: 'Framework',
    icon: 'nextjs',
    category: 'framework',
  },
  {
    name: 'Tailwind',
    type: 'Framework CSS',
    icon: 'tailwindcss',
    category: 'framework',
  },
  {
    name: 'Design System',
    type: 'Design',
    icon: 'designsystem',
    category: 'design',
  },
  {
    name: 'Figma',
    type: 'Design',
    icon: 'figma',
    category: 'design',
  },
  {
    name: 'GraphQL',
    type: 'API',
    icon: 'graphql',
    category: 'api',
  },
  {
    name: 'Git',
    type: 'Versionning',
    icon: 'git',
    category: 'tool',
  },
  {
    name: 'Storybook',
    type: 'Visualisation de composants',
    icon: 'storybook',
    category: 'designsystem',
  },
  {
    name: 'Nuxt',
    type: 'Framework',
    icon: 'nuxt',
    category: 'framework',
  },
  {
    name: 'Vitest',
    type: 'Tests',
    icon: 'vitest',
    category: 'tests',
  },
  {
    name: 'Prismic',
    type: 'Headless CMS',
    icon: 'prismic',
    category: 'cms',
  },
  {
    name: 'Urql',
    type: 'API',
    icon: '',
    category: 'api',
  },
  {
    name: 'API Rest',
    type: 'API',
    icon: '',
    category: 'api',
  },
  {
    name: 'Pinia',
    type: 'State management',
    icon: '',
    category: 'state',
  },
  {
    name: 'VueX',
    type: 'State management',
    icon: '',
    category: 'state',
  },
  {
    name: 'Méthode Agile Scrum',
    type: 'Méthodologie',
    icon: '',
    category: 'methodology',
  },
  {
    name: 'TDD',
    type: 'Méthodologie',
    icon: '',
    category: 'methodology',
  },
  {
    name: 'Histoire',
    type: 'Visualisation de composants',
    icon: '',
    category: 'designsystem',
  },
  {
    name: 'Architecture microservice',
    type: 'API',
    icon: '',
    category: 'api',
  },
]
